Numpy

In [3]:
# numpy는 파이썬에서 과학 계산을 위한 필수 라이브러리
# 대규모 다차원 배열과 행렬 연산을 효율적으로 처리하는 기능을 제공하여 데이터 분석에 널리 사용

# 특징
# 1. 벡터화 연산 : 모델의 성능을 수치로 표현하여 객관적으로 비교 가능
# 2. 다양한 수학 함수 : 삼각 함수, 지수 함수, 통계 함수 등 다양한 수학 함수를 제공
# 3. 배열 생성 및 조작 : 다양한 방법으로 배열을 생성하고, shape을 변경하거나 원한느 요소를 추출
# 4. 선형대수 연산 : 행렬 곱, 역행렬, 고유값 분해 등 선형대수 연산을 지원

Numpy 함수 예시

In [5]:
# np.array()
# 리스트를 Numpy 배열로 변환
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [7]:
# np.arange()
# 주어진 범위 내에서 일정한 간격의 값을 가지는 배열 생성
# arange(시작값, 종료값, 간격) / 종료값 제외
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [13]:
# np.random.rand()
# 0과 1사이의 균일 분포를 따르는 난수 생성
# random : 난수 생성
# rand : 0 ~ 1 난수
arr = np.random.rand(2, 4) # 요소가 4개인 리스트 2개를 생성
print(arr)

[[0.12830214 0.48627016 0.27509685 0.15650144]
 [0.59713934 0.67831922 0.99274481 0.92314161]]


In [12]:
# np.reshape
# 배열의 shape 변경
arr = arr.reshape(1, 9)
print(arr)

[[0.57302333 0.23385967 0.38987038 0.36843275 0.82043135 0.18902301
  0.30850514 0.54915483 0.14922249]]


In [16]:
# np.sum()
# 배열 요소의 합
sum = np.sum([1, 2, 3])
print(sum)


6


In [17]:
# np.mean
# 배열 요소의 평균
mean = np.mean([1, 2, 3])
print(mean)

2.0


In [18]:
# np.std()
# 배열 요소의 표준편차 계산
std = np.std([1, 2, 3])
print(std)

0.816496580927726
