TensorFlow

In [72]:
### TensorFlow를 활용한 y = 2x + 1 선형회귀 모델 예측 예제 ###
import tensorflow as tf
import numpy as np
import matplotlib.pylab as plt
import pandas as pd

# 폰트지정
plt.rcParams['font.family'] = 'Malgun Gothic'

# 마이너스 부호 깨짐 지정
plt.rcParams['axes.unicode_minus'] = False

# 숫자가 지수표현식으로 나올 때 지정
pd.options.display.float_format = '{:.2f}'.format

In [73]:
# 1. 데이터 준비
# x_data: 입력데이터, y_실제값(정답)
x_data = np.array([0, 1, 2, 3, 4], dtype=np.float32)
y_data = np.array([1, 3, 5, 7, 9], dtype=np.float32)

In [74]:
# 2. 모델 정의
# 가중치(w)와 편향(b)의 변수로 정의
w = tf.Variable(0.0) # 가중치 초기화
b = tf.Variable(0.0) # 편향 초기화

In [75]:
# 예측 함수(y = wx + b)
def predict(x):
    return w * x + b

In [76]:
# 3. 손실함수 정의
# 평균 제곱 오차(MSE, Mean Squared Error) 사용
def loss_fn(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))

In [77]:
# 4. 최적화 알고리즘 선택
optimizer = tf.optimizers.SGD(learning_rate=0.1) # 확률적 경사하강법

In [78]:
# 5. 학습 과정
for step in range(100):  # 100번 반복
    with tf.GradientTape() as tape:
        y_pred = predict(x_data)  # 예측값
        loss = loss_fn(y_data, y_pred)  # 손실 계산

    # 가중치와 편향에 대한 경사도 계산 및 업데이트
    gradients = tape.gradient(loss, [w, b])
    print(gradients)
    optimizer.apply_gradients(zip(gradients, [w, b]))

    if step % 10 == 0:  # 10번마다 로그 출력
        print(f"Step {step}, Loss: {loss.numpy()}, w: {w.numpy()}, b: {b.numpy()}")

[<tf.Tensor: shape=(), dtype=float32, numpy=-28.0>, <tf.Tensor: shape=(), dtype=float32, numpy=-10.0>]
Step 0, Loss: 33.0, w: 2.799999952316284, b: 1.0
[<tf.Tensor: shape=(), dtype=float32, numpy=9.600000381469727>, <tf.Tensor: shape=(), dtype=float32, numpy=3.1999998092651367>]
[<tf.Tensor: shape=(), dtype=float32, numpy=-3.2000012397766113>, <tf.Tensor: shape=(), dtype=float32, numpy=-1.2800004482269287>]
[<tf.Tensor: shape=(), dtype=float32, numpy=1.152000904083252>, <tf.Tensor: shape=(), dtype=float32, numpy=0.25600042939186096>]
[<tf.Tensor: shape=(), dtype=float32, numpy=-0.33279865980148315>, <tf.Tensor: shape=(), dtype=float32, numpy=-0.25599950551986694>]
[<tf.Tensor: shape=(), dtype=float32, numpy=0.16895857453346252>, <tf.Tensor: shape=(), dtype=float32, numpy=-0.07168037444353104>]
[<tf.Tensor: shape=(), dtype=float32, numpy=-0.005117230117321014>, <tf.Tensor: shape=(), dtype=float32, numpy=-0.12492707371711731>]
[<tf.Tensor: shape=(), dtype=float32, numpy=0.050992205739021